# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project2-PMS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project2-PMS
  pod 'Firebase/Core'
  pod 'TWMessageBarManager'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'SVProgressHUD'
  pod 'Eureka'
  pod 'BTNavigationDropdownMenu', :git => 'https://github.com/zkrige/BTNavigationDropdownMenu.git'
  pod 'SDWebImage'
  
  target 'Project2-PMSTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
